name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: Install GDAL dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gdal-bin libgdal-dev

    - name: Install dependencies
      run: npm install

    - name: Install pkg
      run: npm install -g pkg

    - name: Package
      run: |
        pkg package.json --targets node18-linux-x64,node18-linux-arm64,node18-win-x64
        mkdir release/
        mv dem2terrain-linux-arm64 release/
        mv node18-linux-arm64 release/
        mv dem2terrain-win-x64.exe release/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
